# Use uma imagem base com Java OpenJDK
FROM openjdk:21

# Diretório de trabalho no contêiner
WORKDIR /app

# Copie o JAR do projeto para o diretório de trabalho
COPY target/Back-end-1.0-SNAPSHOT.jar app.jar

# Exponha a porta em que a aplicação Spring Boot estará rodando
EXPOSE 8080

# Comando para executar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]
